color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.6973436856642365
  lightness: 0.14597393153235316
  saturation: 0.9511937848292291
  rhythmicContrast: 0.9441749809775501
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: omega-0
layout_spectrum: 0.38576768641360104
typography_spectrum: 0.25871656322851777
content: []
title: ω₀ Ventures
description: ''
url: 'https://www.omega-0.com/'
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c652ec51-b79c-4f50-8cc0-2fd682eae48e.gif
